apiVersion: v1
kind: Service
metadata:
  name: ckan
spec:
  selector:
    app: ckan
  ports:
  - name: "5000"
    port: 5000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ckan-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ckan
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ckan
    spec:
      containers:
      - image: orihoch/data4dappl-ckan
        name: ckan
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 50m
        volumeMounts:
        - name: ckan-data
          mountPath: /var/lib/ckan
          subPath: ckan
        - name: etc-ckan-default
          mountPath: /etc/ckan/default
          readOnly: true
      volumes:
      - name: etc-ckan-default
        secret:
          secretName: etc-ckan-default
      - name: ckan-data
        persistentVolumeClaim:
          claimName: ckan-data
